name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest



    steps:
    - name: clonar el repositorio
      uses: actions/checkout@v4

    - name: configurar node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: instalar dependencias
      run: npm install
    
    - name: ejecutar script
      run: npm start
    